Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

b) Верхнетреугольная, ортогональная

c) Нижнетреугольная, ортогональная

d) Матрица, у которой определитель = 1, и все элементы не равны 0

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [3]:
import numpy as np

In [21]:
A = np.array([[-1, 0], [0, -1]])
np.dot(A, A.T)

array([[1, 0],
       [0, 1]])

In [ ]:
# треугольные и при том ортогональные что-то я не уверен что существуют, поправьте если не так

In [33]:
d = np.array([[3, 2], [4, 3]])
print(np.linalg.det(d))

1.0


In [29]:
m = np.array([[2, 2],
              [1, 3]])

w, v = np.linalg.eig(m)
print(w)
print(v)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Уровень 1:
Найдите спектральное разложение матрицы:

m = np.array([[1, 2],
              [2,3]])
print(m)

In [35]:
import numpy as np
m = np.array([[1, 2],
              [2,3]])
print(np.linalg.eig(m))

(array([-0.23606798,  4.23606798]), array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]]))
